spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://${myWork.db.host:localhost}:${myWork.db.port:3306}/${myWork.db.database:mywork}
    username: ${myWork.db.root:root}
    password: ${myWork.db.password:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.backend.pojo
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true




