proPath:
  db:
    host: localhost
    port: 3306
    root: root
    password: 19805601056Bkj@@
    database: propath
  redis:
    host: localhost
    port: 6379
  ai:
    key: sk-yw1RYdnX8JseQuM0mDFEVptf4bEBI1Gc6KxPQeuyGLP9BmFk
    url: https://api.chatanywhere.tech
    model: gpt-4o-mini
  jdbc:
    platform: mariadb
  mail:
    qq: 3165575650@qq.com
    token: qkgdpeallahbdgac

